export const proizvodi = [
    {'name': 'Zenski sumadijski jelek',
      'price':'45',
      'description': 'Reconstruction of a female jelek. A combination of bordeaux plush with a golden cord. Relief work with golden heart and spangles. Available in all sizes, bordeaux, black or dark plush and work with gold or silver heart. You choose.',
      'url':'assets/img/nosnja/nosnja1.jpg',
      'url1': 'assets/img/nosnja/jelek1b.jpg',
      'url2': 'assets/img/nosnja/jelek1a.jpg',
      'url3': 'assets/img/nosnja/jelek1c.jpg',
      'url4': 'assets/img/nosnja/nosnja1.jpg',
    },
    {'name': 'Zenska libada',
      'price':'90',
      'description': 'Reconstruction of the libade by the model of the original. Available in all sizes. Working with a golden / silver heart and a flat wire, on the plush (purple, black, bordeaux, white, dark blue, blue, green) and set with a silk setting.',
      'url':'assets/img/nosnja/nosnja2.jpg',
      'url1': 'assets/img/nosnja/libada1b.jpg',
      'url2': 'assets/img/nosnja/libada1a.jpg',
      'url3': 'assets/img/nosnja/libada1c.jpg',
      'url4': 'assets/img/nosnja/nosnja2.jpg',
      
    },
    {'name': 'Sukure',
      'price':'60',
      'description': 'Reconstruction of the Vlaški sukura. A combination of woven furniture and wool. Available in all sizes and colors.',
      'url':'assets/img/nosnja/rese1a.jpg',
      'url1': 'assets/img/nosnja/rese1a.jpg',
      'url2': 'assets/img/nosnja/rese1b.jpg',
      'url3': 'assets/img/nosnja/rese1c.jpg',
      'url4': 'assets/img/nosnja/rese1d.jpg',
    },
    {'name': 'Kosulja',
      'price':'15',
      'description': 'Reconstruction of women shirts for vlaske (universal type). A combination of chiffon cloth and tape with ornaments and herbal motifs. Available in all sizes, red, blue and green color.',
      'url':'assets/img/nosnja/nosnja4.jpg',
      'url1': 'assets/img/nosnja/nosnja4.jpg',
      'url2': 'assets/img/nosnja/kosulja1a.jpg',
      'url3': 'assets/img/nosnja/kosulja1b.jpg',
      'url4': 'assets/img/nosnja/kosulja1c.jpg',
    },
    {'name': 'Oglavlje',
      'price':'20',
      'description': 'The reconstruction is made by Kobisnica. Scarves (in any color), lace, flowers, ears (fronds), peacock feathers, needles (in different colors).',
      'url':'assets/img/nosnja/kobisnica1aa.jpg',
      'url1': 'assets/img/nosnja/kobisnica1a.jpg',
      'url2': 'assets/img/nosnja/kobisnica1b.jpg',
      'url3': 'assets/img/nosnja/kobisnica1c.jpg',
      'url4': 'assets/img/nosnja/kobisnica1d.jpg',
    },
    {'name': 'Gnjilane jelek',
      'price':'30',
      'description': 'Reconstruction of the firs for Gnjilane / Kosovo Pomoravlje. The combinations of blue silk, golden flat cord, white cord and gold strips. Set siphon with canvas. Available in all sizes.',
      'url':'assets/img/nosnja/kosovo1a.jpg',
      'url1': 'assets/img/nosnja/kosovo1aa.jpg',
      'url2': 'assets/img/nosnja/kosovo1b.jpg',
      'url3': 'assets/img/nosnja/kosovo1c.jpg',
      'url4': 'assets/img/nosnja/kosovo1d.jpg'
    }
];